#!/bin/bash

echo "Stopping service..."
systemctl --user stop linuxmix

# Unload modules/sinks generated by the service
# These are not ideal, as they destroy all instances of those modules
pactl unload-module module-loopback
pactl unload-module module-null-sink

echo "Removing udev rule..."
sudo rm /etc/udev/rules.d/99-linuxmix.rules

echo "Reloading rules..."
sudo udevadm control --reload-rules
sudo udevadm trigger

echo "Removing binary..."
rm ~/.local/bin/linuxmix

echo "Removing service file..."
rm ~/.config/systemd/user/linuxmix.service
rm -r ~/.config/linuxmix

systemctl --user daemon-reload
