name: Rust

on:
  push:
    branches: [ "main" ]
    tags:
      - 'v*'
  pull_request:
    branches: [ "main" ]
    tags:
      - 'v*'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --release
    - name: Tar files
      run: tar -cvzf linuxmix.tar.gz install.sh uninstall.sh target/release/linuxmix
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        if-no-files-found: error
        path: ./linuxmix.tar.gz
        name: linuxmix.tar.gz
    - name: Create release
      uses: ncipollo/release-action@v1
      with:
        tag: v0.0.1
        artifacts: ./linuxmix.tar.gz
